# Generated by Django 4.2.13 on 2024-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_order_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.CharField(default="Default description", max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ready for dispatch", "Ready for dispatch"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=200,
            ),
        ),
    ]
