# Generated by Django 4.2.13 on 2024-10-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_order_description_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=25)),
                ("pieces", models.IntegerField(default=1)),
                (
                    "material",
                    models.CharField(default="default material", max_length=50),
                ),
                (
                    "length",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "breadth",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "thickness",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "pricePerMeter",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="website.order",
                    ),
                ),
            ],
        ),
    ]
