# Generated by Django 4.2.16 on 2024-10-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_orderspecs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderspecs",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderspecs",
                to="website.order",
            ),
        ),
    ]
