# Generated by Django 4.2.16 on 2024-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_orderspecs_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
