# Generated by Django 4.2.16 on 2024-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_picking"),
    ]

    operations = [
        migrations.AddField(
            model_name="picking",
            name="article_id",
            field=models.CharField(default="DEFAULT123", max_length=10),
        ),
    ]
