# Generated by Django 4.2.16 on 2024-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_picking_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picking",
            name="article_id",
            field=models.CharField(default="DEFAULT123", max_length=10, unique=True),
        ),
    ]
