# Generated by Django 4.2.16 on 2024-11-29 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_picking_article_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picking",
            name="article_id",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
