# Generated by Django 4.2.16 on 2024-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_picking_article_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("led_index", models.PositiveIntegerField(unique=True)),
                ("article_id", models.PositiveIntegerField()),
            ],
        ),
    ]
