# Generated by Django 4.2.13 on 2024-12-06 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_ledmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="picking",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterModelTable(
            name="ledmapping",
            table="led_mapping",
        ),
    ]
