# Generated by Django 4.2.16 on 2024-12-06 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_picking_stock_quantity_alter_ledmapping_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picking",
            name="order_spec",
        ),
        migrations.RemoveField(
            model_name="picking",
            name="quantity",
        ),
    ]
