# Generated by Django 4.2.16 on 2024-12-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_picking_article_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "orderspec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_lists",
                        to="website.orderspecs",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_lists",
                        to="website.picking",
                    ),
                ),
            ],
        ),
    ]
