# Generated by Django 4.2.16 on 2024-12-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_pickinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderspecs",
            name="order_spec_id",
            field=models.CharField(default="00000", max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="orderspecs",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pickinglist",
            name="orderspec",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picking_lists",
                to="website.orderspecs",
                to_field="order_spec_id",
            ),
        ),
    ]
